2018-06-01 10:36:58,343 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Duplicate entry 'alex-therieur' for key 'UK_eaj8o68avp2lp29ufm8cdaqqd'
2018-06-01 10:36:58,343 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 10:36:58,377 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - FUNCTION flight_db.TO_DATE does not exist
2018-06-01 10:42:20,133 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Duplicate entry 'alex-therieur' for key 'UK_eaj8o68avp2lp29ufm8cdaqqd'
2018-06-01 10:42:20,133 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 10:42:20,164 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - FUNCTION flight_db.TO_DATE does not exist
2018-06-01 10:42:53,756 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Duplicate entry 'alex-therieur' for key 'UK_eaj8o68avp2lp29ufm8cdaqqd'
2018-06-01 10:42:53,772 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 10:43:58,407 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Duplicate entry 'alex-therieur' for key 'UK_eaj8o68avp2lp29ufm8cdaqqd'
2018-06-01 10:43:58,407 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 10:50:56,635 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clÃ© primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-01 10:50:56,635 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 11:27:27,268 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-01 11:27:27,268 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 14:35:42,994 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-01 14:35:42,994 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-01 14:51:21,871 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-01 14:51:21,887 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-11 16:41:18,862 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-11 16:41:18,863 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 09:24:54,755 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clÃ© primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 09:24:54,760 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 10:16:44,025 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 10:16:44,025 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 10:24:36,049 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 10:24:36,049 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 10:36:45,680 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 10:36:45,680 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 10:42:46,984 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clÃ© primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 10:42:46,984 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 10:55:57,328 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 10:55:57,328 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 14:22:08,345 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 14:22:08,360 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 14:47:46,722 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clÃ© primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 14:47:46,739 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 14:50:04,732 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clÃ© primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 14:50:04,742 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 14:50:13,204 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.m2i.entity.Client.adresse -> com.m2i.entity.Adresse]
2018-06-13 14:51:10,366 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.m2i.entity.Client.adresse -> com.m2i.entity.Adresse]
2018-06-13 15:00:22,657 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Violation dindex unique ou clé primaire: {0}
Unique index or primary key violation: {0}; SQL statement:
insert into Login (password, username, id) values (?, ?, ?) [23505-197]
2018-06-13 15:00:22,657 ERROR main org.hibernate.internal.ExceptionMapperStandardImpl - HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
2018-06-13 16:06:54,557 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper - La base de donnÃ©es est peut-Ãªtre en cours dutilisation: {0}. Solutions posibles: fermer toutes les autres connexions; utilisez le mode serveur
Database may be already in use: {0}. Possible solutions: close all other connection(s); use the server mode [90020-197]
2018-06-13 16:06:54,564 ERROR main org.springframework.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@629adce] to prepare test instance [com.m2i.test.ResaTest@6a282fdd]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [beans.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: myPersistenceUnitName] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:251)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 25 more
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: myPersistenceUnitName] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:963)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
	at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:149)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:370)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:359)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 40 more
Caused by: org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:69)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.jdbcStatement(GenerationTargetToDatabase.java:77)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:53)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:375)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:359)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:241)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:154)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:126)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:112)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:144)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:310)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:467)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:886)
	... 46 more
Caused by: org.h2.jdbc.JdbcSQLException: La base de donnÃ©es est peut-Ãªtre en cours dutilisation: {0}. Solutions posibles: fermer toutes les autres connexions; utilisez le mode serveur
Database may be already in use: {0}. Possible solutions: close all other connection(s); use the server mode [90020-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:188)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:168)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:43)
	... 59 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/Formation/flight_db.mv.db [1.4.197/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	... 82 more
